include:
  - project: 'Recetox/mass-spectrometry/galaxy-tools-deployment'
    file: '/pipeline_templates/.gitlab-ci-docker.yml'
#  - project: 'Recetox/mass-spectrometry/galaxy-tools-deployment'
#    file: '/pipeline_templates/.gitlab-ci-toolshed.yml'
#  - project: 'Recetox/mass-spectrometry/galaxy-tools-deployment'
#    file: '/pipeline_templates/.gitlab-ci-galaxy.yml'

stages:
  - docker_build
#  - toolshed_upload
#  - galaxy_deploy

variables:
  TOOL_PANEL_SECTION_LABEL: "Public"
  DOCKER_REBUILD: "true"

# Docker build and release
docker-build-test:
  extends: .docker-build-test

docker-build-release:
  extends: .docker-build-release

## [Testing Galaxy] tool upload and deployment
#testing-toolshed-instance-upload:
#  extends:
#    - .testing-toolshed-instance-upload
#
#testing-instance-galaxy-deploy:
#  extends: .testing-instance-galaxy-deploy
#
## [UMSA Galaxy] tool upload and deployment
#umsa-toolshed-instance-upload:
#  extends:
#    - .umsa-toolshed-instance-upload
#
#umsa-instance-galaxy-deploy:
#  extends: .umsa-instance-galaxy-deploy